"""E20b: are "more anomalous" positives more useful? Two checks on top of E20.

Same setup, detector and repetitions scheme as E20 (logistic detector only,
3 repetitions). Starting from recipe/rel+div:

  +div/ramp       drift generated by a masked, donor-relative *gapped* step
                  contrast (mean after p + gap minus mean before p, gap
                  U(32, 160) bins left free for the denoiser to fill with a
                  transition) instead of prototypes
  +div/ramp/wide  as +div/ramp, and contrast sizes jittered x U(0.25, 1.5)
                  instead of x U(0.5, 1.5)

Reports recall at 1 % FAR per kind and the share of each gallery's drift
windows that the kNN novelty filter keeps (i.e. that lie outside the nominal
set). Run: PYTHONPATH=src python scripts/testbed_e20b_shape_checks.py [out] [reps]
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

import numpy as np
from sklearn.neighbors import NearestNeighbors

sys.path.insert(0, str(Path(__file__).resolve().parent))
import testbed_e20_detect_utility as e20  # noqa: E402

OUT = Path(sys.argv[1] if len(sys.argv) > 1 else "results/testbed")
REPS = int(sys.argv[2]) if len(sys.argv) > 2 else 3
W, NK = e20.W, e20.N_PER_KIND


def gapped_step_weights(pos: np.ndarray, gaps: np.ndarray, width: int) -> np.ndarray:
    w = np.zeros((len(pos), width))
    for i, (p, g) in enumerate(zip(pos, gaps, strict=True)):
        w[i, p + g :] = 1.0 / (width - p - g)
        w[i, :p] = -1.0 / p
    return w


def drift_by_contrast(den, d, real_drift, *, seed, shell, jitter=(0.5, 1.5), gap_range=(32, 160)):
    r = np.random.default_rng(seed + 991)
    gaps = r.integers(gap_range[0], gap_range[1] + 1, len(d))
    pos = np.array([r.integers(16, W - g - 32) for g in gaps])
    amp, _ = e20.measure_contrast("step", real_drift)
    size = r.choice(amp, len(d)) * r.uniform(jitter[0], jitter[1], len(d))
    w = gapped_step_weights(pos, gaps, W)
    delta = (d * w).sum(axis=1) + size  # donor-relative
    m = np.arange(W)[None, :] >= (pos - 8)[:, None]
    terms = [e20.GuideTerm(0.3, shell.band), e20.GuideTerm(1.0, e20.contrast_fn(w, w * m, delta), project=True)]
    return e20.guided_ddim(den, d, terms, gen_mask=m, rng=np.random.default_rng(seed + 2), nu=0.2, space="x0",
                           final_scale=0.25, n_recur=2, guidance_decay=1.0)


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    arms = ("real_only", "+div", "+div/ramp", "+div/ramp/wide", "+oracle")
    rows: dict[str, list[dict]] = {a: [] for a in arms}
    for rep in range(REPS):
        rng = np.random.default_rng(1000 + rep)  # same draws as E20's repetition rep
        real = e20.few_shot_events(rng)
        x_real = np.concatenate([real[k] for k in e20.KINDS])
        neg = e20.ch.sample(e20.N_NEG, W, rng)
        shell = e20.Shell.from_nominal(e20.enc, e20.ch.sample(512, W, rng), e20.ch.sample(512, W, rng))
        perm = rng.permutation(e20.N_NEG)
        donors = neg[perm[: NK * len(e20.KINDS)]]
        own = np.where(perm[: NK * len(e20.KINDS)] < 1500, perm[: NK * len(e20.KINDS)], -1)
        test_nom = e20.ch.sample(e20.N_TEST_NOM, W, rng)
        kind_test = np.repeat(np.array(e20.KINDS), e20.N_TEST_PER_KIND)
        test_an = np.concatenate([e20.inject(k, e20.ch.sample(e20.N_TEST_PER_KIND, W, rng),
                                             e20.positions(k, e20.N_TEST_PER_KIND, rng),
                                             e20.amplitudes(k, e20.N_TEST_PER_KIND, rng)) for k in e20.KINDS])
        seed = 7 + 100 * rep
        den = e20.DEN["flip_ramp"]
        div, _ = e20.recipe_slices(den, donors, real, seed=seed, shell=shell, relative=True, jitter=(0.5, 1.5),
                                   shift_max=16)
        ramp = div.copy()
        ramp[2 * NK :] = drift_by_contrast(den, donors[2 * NK :], real["drift"], seed=seed, shell=shell)
        wide, _ = e20.recipe_slices(den, donors, real, seed=seed, shell=shell, relative=True, jitter=(0.25, 1.5),
                                    shift_max=16)
        wide[2 * NK :] = ramp[2 * NK :]
        synth = {"+div": div, "+div/ramp": ramp, "+div/ramp/wide": wide,
                 "+oracle": e20.oracle(donors, np.random.default_rng(seed))}
        space = e20.RocketSpace(n_kernels=500, n_components=64, seed=rep).fit(neg[:1000])
        f_neg, f_tn, f_ta, f_real = (space.features(a) for a in (neg, test_nom, test_an, x_real))
        nn = NearestNeighbors(n_neighbors=5).fit(space.embed_features(f_neg[:1500]))
        thr = float(np.quantile(nn.kneighbors(space.embed_features(f_neg[1500:]))[0].mean(axis=1), 0.99))
        _, m = e20.evaluate(f_real, f_neg, f_tn, f_ta, kind_test, detector="logistic")
        rows["real_only"].append(m)
        for name, xs in synth.items():
            fs = space.features(xs)
            _, m = e20.evaluate(np.concatenate([f_real, fs]), f_neg, f_tn, f_ta, kind_test, detector="logistic")
            m["drift kept by kNN filter"] = float(
                (e20.knn_score(nn, space.embed_features(fs[2 * NK :]), own[2 * NK :]) > thr).mean())
            rows[name].append(m)
        print(rep, {a: round(rows[a][-1]["recall@1%FAR"], 3) for a in arms}, flush=True)
    summary = {a: {k: float(np.mean([r[k] for r in v])) for k in v[0]} for a, v in rows.items()}
    (OUT / "e20b_shape_checks.json").write_text(json.dumps({"reps": REPS, "summary": summary, "per_rep": rows}, indent=1))
    for a, s in summary.items():
        print(a, {k: round(v, 3) for k, v in s.items() if k.startswith("recall") or k.startswith("drift")})


if __name__ == "__main__":
    main()
